/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library.management.system;

/**
 *
 * @author SHAKTHI GANAPATHY S
 */
public class Reports extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sanctionyear = new javax.swing.JButton();
        sanctionamountyear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        sanctionyear.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sanctionyear.setText("SANCTION YEAR");
        sanctionyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanctionyearActionPerformed(evt);
            }
        });
        getContentPane().add(sanctionyear);
        sanctionyear.setBounds(260, 210, 383, 68);

        sanctionamountyear.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sanctionamountyear.setText("SANCTION AMOUNT OF YEAR");
        sanctionamountyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanctionamountyearActionPerformed(evt);
            }
        });
        getContentPane().add(sanctionamountyear);
        sanctionamountyear.setBounds(270, 370, 383, 64);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 510, 98, 35);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("             REPORTS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 80, 383, 42);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\smsss\\Downloads\\Library-Backgrounds-Download-Free.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-100, -510, 3545, 1180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sanctionyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanctionyearActionPerformed
        SanctionYear sy=new SanctionYear();
        sy.setVisible(true);
        
    }//GEN-LAST:event_sanctionyearActionPerformed

    private void sanctionamountyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanctionamountyearActionPerformed
            SanctionAmountYear say=new SanctionAmountYear();
            say.setVisible(true);
            
    }//GEN-LAST:event_sanctionamountyearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Main m=new Main();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton sanctionamountyear;
    private javax.swing.JButton sanctionyear;
    // End of variables declaration//GEN-END:variables

    private static class SantionAmountYear {

        public SantionAmountYear() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
